[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6", features = ["csr"] }
leptos_router = { version = "0.6" }
wasm-bindgen = "0.2"
reqwest = { version = "0.11", features = ["json"] }
common = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }

[[bin]]
name = "frontend"
path = "src/main.rs"