//! `SeaORM` Entity. Generated by loco.rs
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "decimal_ledger")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cid: String,         // The Johnny.Decimal code (e.g., "13.4-A")
    pub title: String,
    pub parent_cid: Option<String>,
    pub level: i32,          // Your "depth" logic
    pub path: Option<String>,
    pub content: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

/// Custom logic for the Decimal Ledger
impl Model {
    /// Find a record by its unique CID string
    pub async fn find_by_cid(db: &DatabaseConnection, cid: &str) -> Result<Option<Self>, DbErr> {
        Entity::find_by_id(cid.to_owned()).one(db).await
    }
}