
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create the function that concatenates the ID
CREATE OR REPLACE FUNCTION set_record_id_index()
RETURNS TRIGGER AS $$
BEGIN
    -- We use the NEW.id which was just generated by uuid_generate_v4()
    NEW.id_index := CONCAT('82.2-A-', NEW.id::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;




-- Define a custom Type for your status. 
-- This is much more efficient than strings for filtering thousands of records.
CREATE TYPE index_status AS ENUM (
    'DOWN-PRIORITY', 
    'DOWN-BASIC,', 
    'DOWN-PETTY', 
    'STABLE', 
    'STABLE-ERRORS', 
    'AI-NEEDS-REVIEW', 
    'AI-ERRORS', 
    'NOT-IMPLEMENTED-PRIORITY',
);


CREATE TABLE record_index (

	-- Use UUIDs to prevent ID collisions if you sync between Database and other drives
	------ Generated Key
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),



	------ Description of each index
    description TEXT DEFAULT 'NOT-IMPLEMENTED',  -- Loaded via an AI



	------ Index number
	-- -- 82.2 is the unclassified section
	id_index TEXT,
    id_index TEXT NOT NULL DEFAULT CONCAT('82.2-A-', ), -- 
	


    ------  ------  ------  ------  ------  ------  ------  
	------  ------  -- Status of the Readme of the Index:
	------  -- Options
    ------ Down or not-running
	-- -- Down: Priority -- Fix this index sooner rather than later - Top priority
	-- -- Down: Basic -- Standard error to fix - 2nd highest priority
	-- -- Down: Petty -- Prioritize when there's extra time - Last priority

    ------ Stable or running
	-- -- Stable  -- Good to go 
    -- -- Stable: With Errors  -- Errors with implementation but still running 

    ------ AI implementation
	--------- Reviews the Records for errors, typos, faulty logic, then creates a AI friendly file ("RAG")
	-- -- AI: Needs review -- AI Has not reviewed
	-- -- AI: Errors

    ------ Not implemented
	-- -- Not yet Implemented.   --  Indexes that have not been implemented yet
	-- -- Not yet Implemented: Priority  -- Indexes that have not been made but are a priority to do so

    status index_status DEFAULT 'NOT-IMPLEMENTED',


	------ -- Time stamp at creation time
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	------ -- Time stamp at last update time
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

	
	------ -- Metadata 
	-- Helpful for RAG, PostgreSQL, and scraping useful information for an AI
	metadata JSONB DEFAULT '{}',  -- Store specific tags and weird data elements


	------ -- Index path
	------ All Indexes are in one repo... But it speeds things up
	source_path TEXT DEFAULT ''

);


CREATE INDEX idx_record_metadata_gin ON record_index USING GIN (metadata);




-- Add the Trigger to auto-generate the id_index
CREATE TRIGGER trigger_set_id_index
BEFORE INSERT ON record_index
FOR EACH ROW
EXECUTE FUNCTION set_record_id_index();