// src/envelope.rs
//
// The Envelope is the fundamental unit of data in the Mailroom.
// Every piece of data — text, audio, files, webhooks — gets wrapped
// in an Envelope before the router decides what to do with it.
//
// Think of it like a physical envelope:
//   the outside has routing information (address, return address, type)
//   the inside has the actual content (payload)
// The Mailroom reads the outside. Handlers open the inside.

use chrono::{DateTime, Utc};
// DateTime<Utc> is a timestamp with timezone.
// Utc means we always store in UTC — no timezone ambiguity.
// Utc is a type parameter (like the T in Vec<T>) that tells
// DateTime which timezone system to use.

use serde::{Deserialize, Serialize};
// Both this time — Envelopes go in (Deserialize) and come out (Serialize).
// An API caller sends JSON → we Deserialize into Envelope.
// We store/log an Envelope → we Serialize to JSON.

use std::collections::HashMap;
use std::path::PathBuf;
use uuid::Uuid;


// ── Source ────────────────────────────────────────────────────────────────────
// Where did this Envelope come from?
// An enum ensures only known sources are valid at compile time.
// #[non_exhaustive] means we can add variants later without breaking
// existing match statements — important for a system that will grow.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum Source {
    /// A named peripheral device — audio interface, camera, sensor.
    /// The String is the device's ID as declared in its nest manifest.
    /// Examples: "scarlett-ch1", "pi-camera", "co2-sensor"
    Device(String),

    /// An incoming webhook from an external service (87_Outside-sources).
    /// The String is the service name. Example: "github", "weather-api"
    WebHook(String),

    /// A file written or dropped manually by the user.
    Manual,

    /// Data generated by an AI model.
    /// The String is the model ID. Example: "qwen_qwen3.5-0.8b", "meditron"
    Internal(String),

    /// Another Mailroom node forwarding an envelope.
    /// The String is the forwarding node's ID. Example: "pi", "island"
    Forwarded(String),

    /// Anything not covered above.
    /// The String describes the source for logging and debugging.
    Other(String),
}

// ── Payload ───────────────────────────────────────────────────────────────────
// The actual content inside the Envelope.
// Each variant holds a different kind of data.
//
// Rust concept — enum with data:
//   Unlike enums in many languages, Rust enum variants can hold values.
//   This makes enums much more powerful — they're closer to
//   "tagged unions" or "sum types" in type theory.
//   Pattern matching on a Payload lets handlers extract exactly
//   the data they need, and the compiler ensures they handle all cases.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", content = "data", rename_all = "snake_case")]
// `tag` and `content` control how serde serializes this enum to JSON.
// With these attributes, a Text payload serializes as:
//   { "kind": "text", "data": "hello world" }
// instead of the default:
//   { "Text": "hello world" }
// This is more readable and conventional in JSON APIs.
pub enum Payload {
    /// Plain text or markdown content.
    /// Journal entries, notes, dictated text.
    Text(String),

    /// Structured JSON data.
    /// Biometric readings, financial records, webhook bodies.
    /// serde_json::Value is a dynamically-typed JSON value —
    /// it can hold any valid JSON without a fixed schema.
    Json(serde_json::Value),

    /// Raw binary data.
    /// Audio samples, images before processing.
    /// Vec<u8> is a growable array of bytes (u8 = unsigned 8-bit integer).
    Bytes(Vec<u8>),

    /// A path to a file on the local filesystem.
    /// Used when the content is too large to hold in memory,
    /// or when the file already exists on disk (e.g. an HLS segment).
    /// The Mailroom resolves this path relative to /storage/Library.
    FilePath(PathBuf),

    /// A URL pointing to external content.
    /// Used by 87_Outside-sources for web content, feeds, webhooks.
    Url(String),
}

// ── Envelope ──────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Envelope {
    /// Unique identifier for this envelope.
    /// Generated at creation time. Used to track the envelope
    /// through the routing pipeline and into the event log.
    pub id: Uuid,

    /// Where this data belongs in the JD system.
    /// The registry looks this up to find routing rules.
    /// Examples: "34.2" (Journal), "35.2" (Physical Health), "83" (Scratchpad)
    ///
    /// Optional — if None, the Mailroom attempts to classify it
    /// using the AI layer before routing. Unclassified envelopes
    /// queue in 82.2_Unclassified until resolved.
    pub jd_address: Option<String>,

    /// The MIME-style data type of the payload.
    /// Used alongside jd_address to select the right handler.
    /// Examples: "text/journal", "text/markdown", "data/biometric",
    ///           "media/audio", "media/image", "application/json"
    pub data_type: String,

    /// Where this envelope came from.
    pub source: Source,

    /// The actual content.
    pub payload: Payload,

    /// When this envelope was created (not when it was received —
    /// the source sets this, so it reflects when the data was produced).
    pub created_at: DateTime<Utc>,

    /// When the Mailroom received this envelope.
    /// May differ from created_at for queued or delayed envelopes.
    pub received_at: DateTime<Utc>,

    /// Arbitrary key-value metadata.
    /// Each source can attach context that doesn't fit the standard fields.
    /// Examples:
    ///   "duration_secs" → "30"      (audio clip)
    ///   "channel"       → "ch1"     (Scarlett source)
    ///   "webhook_event" → "push"    (GitHub webhook)
    ///   "word_count"    → "342"     (journal entry)
    #[serde(default)]
    // default: if `meta` is missing from incoming JSON, use empty HashMap
    pub meta: HashMap<String, String>,

    /// Free-form tags — presence means yes, absence means no. Unlike
    /// `meta`, which is one value per key, tags are inherently
    /// multi-valued (a recipe can be both "vegetarian" and
    /// "gluten-free" at once), so a flat Vec (a set, deduped by
    /// convention rather than by type) fits better than a HashMap of
    /// booleans would — there's nothing to store for the tags that
    /// don't apply. Which tags are meaningful for a given Nest is
    /// documented by that Nest's own `known_tags`, not enforced here.
    #[serde(default)]
    pub tags: Vec<String>,
}

/// What a caller sends to POST /envelope.
/// The Mailroom generates id, created_at, and received_at itself —
/// callers shouldn't need to know about UUIDs or timestamps.
#[derive(Debug, Deserialize)]
pub struct InboundEnvelope {
    pub source:     Source,
    pub data_type:  String,
    pub payload:    Payload,
    pub jd_address: Option<String>,

    #[serde(default)]
    pub meta: HashMap<String, String>,

    #[serde(default)]
    pub tags: Vec<String>,

    /// Callers may optionally provide a created_at timestamp
    /// if the data was produced earlier (e.g. a queued clip).
    /// If absent, the Mailroom uses the current time.
    pub created_at: Option<DateTime<Utc>>,
}

impl InboundEnvelope {
    /// Promote an InboundEnvelope into a full Envelope.
    /// Generates the id and sets received_at to now.
    pub fn into_envelope(self) -> Envelope {
        let now = Utc::now();
        Envelope {
            id:          Uuid::new_v4(),
            source:      self.source,
            data_type:   self.data_type,
            payload:     self.payload,
            jd_address:  self.jd_address,
            meta:        self.meta,
            tags:        self.tags,
            created_at:  self.created_at.unwrap_or(now),
            // Use caller's timestamp if provided, otherwise now.
            received_at: now,
        }
    }
}

impl Envelope {
    /// Create a new Envelope with generated ID and current timestamps.
    ///
    /// This is the main constructor — sources call this to wrap their data.
    pub fn new(
        source:     Source,
        data_type:  impl Into<String>,
        payload:    Payload,
        jd_address: Option<impl Into<String>>,
    ) -> Self {
        let now = Utc::now();
        // Utc::now() returns the current time as DateTime<Utc>.
        // We capture it once so created_at and received_at are identical
        // on a freshly created envelope. They diverge when an envelope
        // was created earlier and queued (e.g. Island was offline).

        Self {
            id:          Uuid::new_v4(),
            // Uuid::new_v4() generates a random UUID.
            // e.g. "550e8400-e29b-41d4-a716-446655440000"
            // Statistically guaranteed unique — no coordination needed.

            jd_address:  jd_address.map(|a| a.into()),
            // Option::map applies a function to the inner value if Some,
            // leaves None as None.
            // jd_address.map(|a| a.into()) converts Some("34.2") to
            // Some(String::from("34.2")), or leaves None as None.

            data_type:   data_type.into(),
            source,
            // Rust shorthand: when field name == variable name, write once.

            payload,
            created_at:  now,
            received_at: now,
            meta:        HashMap::new(),
            tags:        Vec::new(),
        }
    }

    /// Attach a tag. Returns Self so calls can be chained, same as
    /// `with_meta` — Envelope::new(...).with_tag("vegetarian").with_tag("quick")
    pub fn with_tag(mut self, tag: impl Into<String>) -> Self {
        self.tags.push(tag.into());
        self
    }

    /// Attach a metadata key-value pair.
    /// Returns Self so calls can be chained:
    ///   Envelope::new(...).with_meta("channel", "ch1").with_meta("duration", "30")
    pub fn with_meta(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        // `mut self` — we take ownership of the envelope and mutate it.
        // This is the builder pattern: consume self, modify, return self.
        // The caller can no longer use the original — only the returned value.
        self.meta.insert(key.into(), value.into());
        self
        // Return the modified envelope. No semicolon = implicit return.
    }

    /// Mark this envelope as queued — update received_at to now.
    /// Called when an envelope was created offline and is being
    /// processed after Island came back online.
    pub fn mark_received(mut self) -> Self {
        self.received_at = Utc::now();
        self
    }

    /// Returns true if this envelope has no JD address yet.
    /// Unaddressed envelopes need AI classification before routing.
    pub fn needs_classification(&self) -> bool {
        // &self — immutable borrow. We're just reading, not modifying.
        self.jd_address.is_none()
        // Option::is_none() returns true if the value is None.
        // No explicit return needed — last expression is returned.
    }
}